#!/usr/bin/env bash
# Compile every Kapitan target in the inventory.

printf "Kapitan version: "
kapitan --version

echo "Building kapitan targets from ${SOURCE_PATH} to ${BUILD_PATH} ..."
cd ${SOURCE_PATH}; kapitan compile --use-go-jsonnet --output-path ${BUILD_PATH} --search-paths '.' './vendor' --parallelism 8
