#!/usr/bin/env bash
# Compile one Kapitan target from its inventory.

printf "Kapitan version: "
kapitan --version

echo "Building kapitan target ${SOURCE_TARGET} from ${SOURCE_PATH} to ${BUILD_PATH} ..."
cd ${SOURCE_PATH}; kapitan compile --use-go-jsonnet --output-path ${BUILD_PATH} --search-paths '.' './vendor' --target ${SOURCE_TARGET}
